server.port: 80

logging:
  level:
    ROOT: INFO
    com.little.backup.box.commands: DEBUG

bot:
  enable: false
  token: 
  username: 
  creatorid: 
  
folder:
  home: /home/pi/BACKUP
  dev:
    sda1: /dev/sda1
    sdb1: /dev/sdb1
  mountPoint:
    card: /media/card
    microsd: /media/microsd
    storage: /media/storage